version: '3.8'
services:

  # NGINX PROXY
  # https://github.com/NginxProxyManager/nginx-proxy-manager
  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "82:80"
      - "443:443"
      - "81:81"
    volumes:
      - /apps/dnd/nginx/data:/data
      - /apps/dnd/nginx/letsencrypt:/letsencrypt
    networks:
      - public-proxy # PUBLIC SERVICES MUST CONNECT TO THIS NETWORK

  # NODERED
  # https://nodered.org/docs/getting-started/docker
  node-red:
    image: nodered/node-red:latest-18
    container_name: nodered
    restart: unless-stopped
    volumes:
      - /apps/dnd/nodered:/data
    environment:
      - TZ=America/Denver
      - NODE_RED_CREDENTIAL_SECRET="XXX"
    networks:
      - public-proxy

# FOUNDRY
# https://github.com/felddy/foundryvtt-docker
  foundryvtt:
    container_name: foundryvtt
    image: felddy/foundryvtt:release
    hostname: map.dnd.epklabs
    restart: unless-stopped
    networks:
      - public-proxy
    volumes:
      - /apps/dnd/foundryvtt:/data
      - /apps/dnd/5etools/homebrew:/data/Data/assets/homebrew
    environment:
      - UID=1001
      - GID=1001
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - CONTAINER_CACHE=/data/cache
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - FOUNDRY_HOSTNAME=dnd.epklabs
      - VIRTUAL_HOST=dnd.epklabs
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - VIRTUAL_PORT=30000
      - TIMEZONE='America/Denver'
      - FOUNDRY_UID=1001
      - FOUNDRY_GID=1001
    ports:
      - 30000:30000/tcp
    links:
      - ddb-proxy:ddb-proxy
    env_file:
      - .env

# CONNECTS FOUNDRY to D&D BEYOND
# https://github.com/MrPrimate/ddb-proxy
  ddb-proxy:
    image: ghcr.io/mrprimate/ddb-proxy:latest
    container_name: ddb-proxy
    restart: unless-stopped
    networks:
      - public-proxy

# 5E TOOLS
# https://github.com/Jafner/5etools-docker
  5etools:
    restart: unless-stopped
    container_name: 5etools
    image: jafner/5etools-docker
    volumes:
      - /apps/dnd/5etools:/usr/local/apache2/htdocs
      - /apps/dnd/5etools-homebrew:/usr/local/apache2/htdocs/homebrew
    environment:
      - SOURCE=GITHUB
      - IMG=TRUE
    networks:
      - public-proxy

# HOMEBREWERY
# https://github.com/naturalcrit/homebrewery
  homebrewdb:
    image: mongo:latest
    container_name: homebrewdb
    volumes:
      - /apps/dnd/homebrewery/db:/data/db
    networks:
      - homebrew-internal
  homebrew:
    restart: unless-stopped
    container_name: homebrew
    # FIRST: clone the repo, then pull node:18-alpine
    # git clone https://github.com/naturalcrit/homebrewery
    # docker pull node:18-alpine
    build:
      context: ./homebrewery
      dockerfile: Dockerfile
    image: homebrewery
    depends_on:
      - homebrewdb
    environment:
      MONGODB_URI: mongodb://homebrewdb/homebrewery
    networks:
      - homebrew-internal
      - public-proxy

# OUTLINE STACK
#
# DB FOR OUTLINE
  postdb:
    image: postgres:13
    restart: unless-stopped
    container_name: postdb
    environment:
      - POSTGRES_USER=XXX
      - POSTGRES_PASSWORD=XXX
      - POSTGRES_DB=XXX
    volumes:
      - /home/ubuntu/dbpost:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - outline-internal
# OUTLINE DB BACKUP
  postdb_backup:
    image: postgres:13
    depends_on:
      - postdb
    volumes:
      - /mnt/server/Backups:/backup
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h postdb -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /backup/$$(date +%Y-%m-%d-%H-%M-%S)-outline-postgres.dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /backup/*.dump | head -n -30 | xargs rm -f
        sleep 86400
      done"
    environment:
      - POSTGRES_USER=XXX
      - POSTGRES_PASSWORD=XXX 
      - POSTGRES_DB=XXX
    networks:
      - outline-internal
# REDIS FOR OUTLINE
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
    networks:
      - outline-internal
# OUTLINE WIKI
# https://github.com/outline/outline
  outline:
    image: outlinewiki/outline:0.78.0
    container_name: outline
    restart: unless-stopped
    # USE THIS TO UPGRADE
    #command: sh -c "sleep 5 && yarn db:migrate --env=production-ssl-disabled"
    # USE THIS TO RUN PRODUCTION SERVICE
    command: yarn start --env=production-ssl-disabled
    depends_on:
      - postdb
      - redis
    links:
      - postdb:postdb
      - redis:redis
    env_file:
      - /apps/dnd/outline/outline.env
    ports:
      - "1661:80"
    volumes:
      - /apps/dnd/outline/data:/var/lib/outline/data
    networks:
      - outline-internal
      - public-proxy

#
# OPTIONAL OUTLINE INTEGRATIONS
#
  # DRAWIO
  # https://github.com/jgraph/docker-drawio
  drawio:
    image: jgraph/drawio
    container_name: drawio
    restart: unless-stopped
    environment:
      - PUBLIC_DNS=lore.dnd.epklabs.com
      - DRAWIO_BASE_URL=lore.dnd.epklabs.com
      - DRAWIO_GOOGLE_CLIENT_ID=XXX
      - DRAWIO_GOOGLE_CLIENT_SECRET=XXX
      - DRAWIO_GOOGLE_APP_ID=XXX
      - DRAWIO_GOOGLE_VIEWER_CLIENT_ID=XXX
      - DRAWIO_GOOGLE_VIEWER_CLIENT_SECRET=XXX
      - DRAWIO_GOOGLE_VIEWER_APP_ID=XXX
      - KEYSTORE_PASS=XXX
    networks:
      - public-proxy


# GHOST STACK
#
# GHOST
# https://github.com/TryGhost/Ghost
  ghost_dungeon:
    image: ghost:latest
    restart: always
    container_name: ghost_dungeon
    networks:
      - public-proxy
      - internal-db
    links:
      - db:db
    depends_on:
      - db
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=XXX
      - database__connection__password=XXX
      - database__connection__database=XXX
      - url=https://www.dnd.epklabs.com
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
      - mail__transport=SMTP
      - mail__options__host=smtp.mailgun.org
      - mail__options__port=587
      - mail__options__auth__user=XXX
      - mail__options__auth__pass=XXX
      - mail__from="Dungeons & Distractions <ellie@epklabs.com>"
    volumes:
      - /apps/dnd/ghost:/var/lib/ghost
# GHOST DB
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XXX
    volumes:
      - /apps/dnd/db:/var/lib/mysql
    networks:
      - internal-db
# GHOST DB BACKUP
  db_backup:
     image: databack/mysql-backup
     restart: always
     container_name: db_backup
     user: "0" # needed for local volume
     environment:
       - DB_DUMP_FREQ=1440 # once a day
       - DB_SERVER=db
       - DB_USER=XXX
       - DB_PASS=XXX
       - DB_NAMES=ghost
       - DB_DUMP_TARGET=/backup
       - DB_DUMP_SAFECHARS=true
     links:
       - db:db
     networks:
       - internal-db
     volumes:
       - /mnt/server/Backups:/backup

# RED DISCORD BOT
# https://github.com/PhasecoreX/docker-red-discordbot
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - /apps/dnd/redbot:/data
    environment:
      - TOKEN=XXX
      - PREFIX=.
      - TZ=America/Denver
      - PUID=1000

networks:
  public-proxy:
  internal-db:
  outline-internal:
  homebrew-internal:
